version: 1
builder:
  configs:
  - platform: ios
    scheme: CombineInterception

  - platform: macos-spm
    scheme: CombineInterception

  - platform: macos-xcodebuild
    scheme: CombineInterception

  - platform: tvos
    scheme: CombineInterception

  - platform: watchos
    scheme: CombineInterception

  - documentation_targets:
    - CombineInterception
